print("Pycharm Practice File 1")
print("received by github and now sending back to Pycharm")
print("trying to send back to github with commit and push")
print("send back to pycharm again via pycharm pull")
print("send back to pycharm again via pycharm git clone")
